package com.t2.export.service;

import com.t2.shared.ExportRequest;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.*;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.Map;

@Slf4j
@Service
public class ExcelExportService {

    public byte[] export(ExportRequest req) throws IOException {
        log.info("Exporting {} rows × {} cols", req.rows().size(), req.columns().size());

        try (XSSFWorkbook wb = new XSSFWorkbook()) {
            XSSFSheet sheet = wb.createSheet("Results");
            List<String> cols = req.columns();

            // Styles
            CellStyle titleSt   = titleStyle(wb);
            CellStyle headerSt  = headerStyle(wb);
            CellStyle evenSt    = evenStyle(wb);
            CellStyle oddSt     = oddStyle(wb);
            CellStyle numEvenSt = numStyle(wb, false);
            CellStyle numOddSt  = numStyle(wb, true);
            CellStyle footSt    = footStyle(wb);

            int r = 0;

            // Title
            Row title = sheet.createRow(r++);
            title.setHeightInPoints(22);
            Cell tc = title.createCell(0);
            tc.setCellValue("Export: " + req.fileName() + "  |  Query: " + req.prompt());
            tc.setCellStyle(titleSt);
            if (cols.size() > 1) sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, cols.size() - 1));

            sheet.createRow(r++); // spacer

            // Header
            Row hdr = sheet.createRow(r++);
            hdr.setHeightInPoints(18);
            for (int c = 0; c < cols.size(); c++) {
                Cell cell = hdr.createCell(c);
                cell.setCellValue(cols.get(c).toUpperCase().replace("_", " "));
                cell.setCellStyle(headerSt);
            }

            // Data rows
            int dataStart = r;
            for (Map<String, Object> row : req.rows()) {
                Row dr = sheet.createRow(r++);
                dr.setHeightInPoints(15);
                boolean even = (r - dataStart) % 2 == 0;
                for (int c = 0; c < cols.size(); c++) {
                    Cell cell = dr.createCell(c);
                    Object val = row.get(cols.get(c));
                    if (val instanceof Number n) {
                        cell.setCellValue(n.doubleValue());
                        cell.setCellStyle(even ? numEvenSt : numOddSt);
                    } else if (val instanceof Boolean b) {
                        cell.setCellValue(b);
                        cell.setCellStyle(even ? evenSt : oddSt);
                    } else {
                        cell.setCellValue(val != null ? val.toString() : "");
                        cell.setCellStyle(even ? evenSt : oddSt);
                    }
                }
            }

            // Footer
            Row foot = sheet.createRow(r);
            Cell fc = foot.createCell(0);
            fc.setCellValue("Total rows: " + req.rows().size() + "  |  Generated by ReportPrompt AI");
            fc.setCellStyle(footSt);
            if (cols.size() > 1) sheet.addMergedRegion(new CellRangeAddress(r, r, 0, cols.size() - 1));

            // Column widths
            for (int c = 0; c < cols.size(); c++) {
                sheet.autoSizeColumn(c);
                sheet.setColumnWidth(c, Math.min(sheet.getColumnWidth(c) + 512, 50 * 256));
            }
            sheet.createFreezePane(0, 3);
            if (!cols.isEmpty())
                sheet.setAutoFilter(new CellRangeAddress(2, r - 1, 0, cols.size() - 1));

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            wb.write(out);
            return out.toByteArray();
        }
    }

    // ── Styles ──────────────────────────────────────────────────────────────

    private CellStyle titleStyle(XSSFWorkbook wb) {
        CellStyle s = wb.createCellStyle();
        XSSFFont f = wb.createFont(); f.setBold(true); f.setFontHeightInPoints((short)13);
        f.setColor(new XSSFColor(new byte[]{(byte)28,(byte)78,(byte)128}, null));
        s.setFont(f); s.setVerticalAlignment(VerticalAlignment.CENTER);
        s.setFillForegroundColor(new XSSFColor(new byte[]{(byte)240,(byte)245,(byte)252}, null));
        s.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        return s;
    }

    private CellStyle headerStyle(XSSFWorkbook wb) {
        CellStyle s = wb.createCellStyle();
        s.setFillForegroundColor(new XSSFColor(new byte[]{(byte)28,(byte)78,(byte)128}, null));
        s.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        XSSFFont f = wb.createFont(); f.setBold(true); f.setFontHeightInPoints((short)11);
        f.setColor(new XSSFColor(new byte[]{(byte)255,(byte)255,(byte)255}, null));
        s.setFont(f); s.setAlignment(HorizontalAlignment.CENTER);
        s.setVerticalAlignment(VerticalAlignment.CENTER); borders(s, BorderStyle.THIN);
        return s;
    }

    private CellStyle evenStyle(XSSFWorkbook wb) {
        CellStyle s = wb.createCellStyle(); s.setVerticalAlignment(VerticalAlignment.CENTER);
        borders(s, BorderStyle.HAIR); return s;
    }

    private CellStyle oddStyle(XSSFWorkbook wb) {
        CellStyle s = wb.createCellStyle();
        s.setFillForegroundColor(new XSSFColor(new byte[]{(byte)235,(byte)242,(byte)252}, null));
        s.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        s.setVerticalAlignment(VerticalAlignment.CENTER); borders(s, BorderStyle.HAIR); return s;
    }

    private CellStyle numStyle(XSSFWorkbook wb, boolean odd) {
        CellStyle s = odd ? oddStyle(wb) : evenStyle(wb);
        s.setAlignment(HorizontalAlignment.RIGHT);
        s.setDataFormat(wb.createDataFormat().getFormat("#,##0.##")); return s;
    }

    private CellStyle footStyle(XSSFWorkbook wb) {
        CellStyle s = wb.createCellStyle();
        s.setFillForegroundColor(new XSSFColor(new byte[]{(byte)220,(byte)230,(byte)245}, null));
        s.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        XSSFFont f = wb.createFont(); f.setBold(true); f.setFontHeightInPoints((short)10); s.setFont(f);
        borders(s, BorderStyle.THIN); return s;
    }

    private void borders(CellStyle s, BorderStyle b) {
        s.setBorderTop(b); s.setBorderBottom(b); s.setBorderLeft(b); s.setBorderRight(b);
    }
}
